services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - mynetwork

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
